
import React from "react";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
require('dotenv').config(".env.local");

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col items-center`}>

            {/* Headder */}
            <div className="w-full max-w-6xl flex justify-between items-center px-6 py-4">
                <h1 className="text-3xl font-bold text-(--primary)">SmartAid</h1>
                <header className="flex gap-4">
                  <SignedOut>
                    <SignInButton />
                    <SignUpButton>
                      <button className="bg-(--primary) text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                        Sign Up
                      </button>
                    </SignUpButton>
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                </header>
            </div>


          <div className="w-full max-w-6xl flex flex-col items-center justify-center px-6 py-10">
            {children}
          </div>
        </body>
      </html>
      
    </ClerkProvider>
  )
}
